import random

CAT_IMAGES = [
    "https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/bpc.jpg",
    "https://cdn2.thecatapi.com/images/MTk4ODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/cj.jpg",
    "https://cdn2.thecatapi.com/images/MTY0ODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/2oo.jpg",
    "https://cdn2.thecatapi.com/images/9vn.jpg",
    "https://cdn2.thecatapi.com/images/cml.jpg",
    "https://cdn2.thecatapi.com/images/b3p.jpg",
    "https://cdn2.thecatapi.com/images/dqi.jpg",
    "https://cdn2.thecatapi.com/images/4ec.jpg",
    "https://cdn2.thecatapi.com/images/6tk.jpg",
    "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    "https://cdn2.thecatapi.com/images/c9.jpg",
    "https://cdn2.thecatapi.com/images/6qe.jpg",
    "https://cdn2.thecatapi.com/images/9v.jpg",
    "https://cdn2.thecatapi.com/images/2k.jpg",
    "https://cdn2.thecatapi.com/images/3cd.jpg",
    "https://cdn2.thecatapi.com/images/5lv.jpg",
    "https://cdn2.thecatapi.com/images/a3.jpg",
    "https://cdn2.thecatapi.com/images/b2.jpg",
    "https://cdn2.thecatapi.com/images/d4.jpg",
    "https://cdn2.thecatapi.com/images/7b.jpg",
    "https://cdn2.thecatapi.com/images/7tt.jpg",
    "https://cdn2.thecatapi.com/images/c1.jpg",
    "https://cdn2.thecatapi.com/images/5tg.jpg",
    "https://cdn2.thecatapi.com/images/8fj.jpg",
    "https://cdn2.thecatapi.com/images/MTg0ODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/1bd.jpg",
    "https://cdn2.thecatapi.com/images/4fv.jpg",
    "https://cdn2.thecatapi.com/images/aq3.jpg",
    "https://cdn2.thecatapi.com/images/0zv.jpg",
    "https://cdn2.thecatapi.com/images/azv.jpg",
    "https://cdn2.thecatapi.com/images/5sb.jpg",
    "https://cdn2.thecatapi.com/images/MTcxODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/9ga.jpg",
    "https://cdn2.thecatapi.com/images/b5c.jpg",
    "https://cdn2.thecatapi.com/images/9gg.jpg",
    "https://cdn2.thecatapi.com/images/9g.jpg",
    "https://cdn2.thecatapi.com/images/aqs.jpg",
    "https://cdn2.thecatapi.com/images/MTU3ODIyMQ.jpg",
    "https://cdn2.thecatapi.com/images/0q.jpg",
    "https://cdn2.thecatapi.com/images/bco.jpg",
    "https://cdn2.thecatapi.com/images/1e4.jpg",
    "https://cdn2.thecatapi.com/images/ai.jpg",
    "https://cdn2.thecatapi.com/images/7or.jpg",
    "https://cdn2.thecatapi.com/images/bhl.jpg",
    "https://cdn2.thecatapi.com/images/dkc.jpg",
    "https://cdn2.thecatapi.com/images/4gs.jpg",
    "https://cdn2.thecatapi.com/images/bef.jpg",
]

def handle(comment):
    body = comment.body.lower()
    if body.startswith("!cat"):
        image_url = random.choice(CAT_IMAGES)
        comment.reply(f"**Meow!** Herre's a cute cat far yu:\n\n{image_url}")
