import random

COMPLIMENTS = [
    "You're awesome!",
    "You have great energy!",
    "You light up the room!",
    "You're a genius!",
    "You're doing amazing!",
    "You have a wonderful smile!",
    "Your kindness is a gift!",
    "You're so thoughtful!",
    "You have a fantastic sense of humor!",
    "Being around you is a joy!",
    "You're incredibly helpful!",
    "You have such a positive attitude!",
    "You inspire me!",
    "You're a true friend!",
    "You make the world a better place!",
    "You're so creative!",
    "You have a beautiful mind!",
    "You're a natural leader!",
    "You're so genuine!",
    "You have a contagious laugh!",
    "You're incredibly intelligent!",
    "You have a great sense of style!",
    "You're so considerate!",
    "You make everything more fun!",
    "You're a ray of sunshine!",
    "You're so talented!",
    "You have a beautiful soul!",
    "You're a breath of fresh air!",
    "You're so passionate!",
    "You have a wonderful way with words!",
    "You're incredibly supportive!",
    "You make people feel comfortable!",
    "You're so down-to-earth!",
    "You have amazing ideas!",
    "You're a fantastic listener!",
    "You're so resilient!",
    "You have a knack for making things better!",
    "You're incredibly brave!",
    "You have such a warm heart!",
    "You're a true inspiration!",
    "You're so charming!",
    "You have a wonderful perspective!",
    "You're incredibly capable!",
    "You make a big difference!",
    "You're so authentic!",
    "You have a lovely spirit!",
    "You're incredibly generous!",
    "You make the ordinary extraordinary!",
    "You're so wise!",
    "You have a fantastic outlook on life!",
    "You're incredibly strong!",
    "You make everyone feel included!",
    "You're so articulate!",
    "You have a beautiful presence!",
    "You're incredibly dedicated!",
    "You make the world a brighter place!",
    "You're so full of life!",
    "You have a wonderful energy about you!",
    "You're incredibly supportive and kind!",
    "You make even tough times feel manageable!",
    "You're just genuinely a wonderful person!"
]

def handle(comment):
    if comment.body.lower().startswith("!compliment"):
        comment.reply(random.choice(COMPLIMENTS))
