import random

JOKES = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "How do you organize a space party? You planet.",
    "Want to hear a construction joke? I'm still working on it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the bicycle fall over? Because it was two tired.",
    "Dad, did you get a haircut? No, I got them all cut!",
    "How do you make a tissue dance? You put a little boogie in it.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Have you heard about the restaurant on the moon? I heard the food was good but it had no atmosphere.",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the golfer wear two pairs of pants? In case he got a hole-in-one!",
    "What do you call a sad strawberry? A blueberry.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How does a penguin build its house? Igloos it together.",
    "What do you call a boomerang that won't come back? A stick.",
    "Why did the coffee file a police report? It got mugged!",
    "What's brown and sticky? A stick!",
    "Why did the picture go to jail? Because it was framed!",
    "What musical instrument is found in the bathroom? A tuba toothpaste.",
    "Why did the cookie go to the doctor? Because it felt crummy.",
    "How do you make seven even? Take away the 's'!",
    "What do you call a lazy baby kangaroo? A pouch potato chip.",
    "Why did the belt go to jail? For public waist-ing!",
    "What do you call a sheep with no legs? A cloud!",
    "Why did the broom get a bad grade? It was always sweeping things under the rug!",
    "What do you call a fish made of peanut butter? A peanut butter and jelly fish!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "What do you call a car with no wheels? An immobile!",
    "Why did the computer go to therapy? It had too many issues!",
    "What do you call a door that can't close? A door that's ajar!",
    "Why did the music teacher go to jail? For treble-ing his students!",
    "What do you call a rabbit detective? A hare-y investigator!",
    "Why did the painter go to jail? He was framed!",
    "What do you call a fake alligator? A crocodile!",
    "Why did the snowman name his dog 'Frost'? Because bites!",
    "What do you call a sad pepper? A melancholy!",
    "Why did the fly fly? Because the spider spied her!",
    "What do you call a smart phone? A wise device!",
    "Why did the golfer wear colorful pants? He wanted to have a good fairway!",
    "How do you get a squirrel to like you? Act like a nut.",
    "What do you call a nervous walrus? A jittery blubber.",
    "Why did the orchestra stop playing? Because they lost their conductor!",
    "What do you call a number that just can't stand still? A roamin' numeral.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "What's a pirate's favorite letter? You'd think it's 'R' but it's the 'C' they love!",
    "Why did the cookie go to the hospital? Because he felt crummy.",
    "How do you make a hot dog stand? You take away its chair!",
    "What did the grape do when he got stepped on? He let out a little wine!",
    "Why did the banana go to the hospital? Because it wasn't peeling well!",
    "What musical instrument is found in the bathroom? A tuba toothpaste!",
    "Why did the bicycle fall over? Because it was two tired!",
    "What do you call a lazy kangaroo? A pouch potato!",
    "How do you catch a unique rabbit? Unique up on it!",
    "Why don't eggs tell jokes? They'd crack each other up!"
]

def handle(comment):
    if comment.body.lower().startswith("!dadjoke"):
        comment.reply(random.choice(JOKES))
