import random

DARES = [
    "Say the alphabet backwards!",
    "Post your most recent photo with no context.",
    "Tell a joke — even if it's bad!",
    "Comment with only emojis on the next post.",
    "Make your next comment in all caps!",
    "Sing your favorite song out loud (even if you're alone!).",
    "Do 10 jumping jacks right now.",
    "Imitate your favorite animal.",
    "Describe your current surroundings in three words.",
    "Share a random fact you know.",
    "Write a short poem about your day so far.",
    "Send a silly voice note to a friend.",
    "Draw a picture of a cat and share it (no judging!).",
    "Do a silly dance for 15 seconds.",
    "Tell us your biggest fear (in a non-serious way!).",
    "Name three things you're grateful for today.",
    "Try to touch your nose with your tongue.",
    "Make a funny face and hold it for 10 seconds.",
    "Share your favorite childhood memory in one sentence.",
    "Pretend to be a robot in your next comment.",
    "Whisper a secret (even if it's made up!).",
    "Do a little air guitar solo.",
    "Describe your favorite food using only adjectives.",
    "Tell us what you're wearing right now (be honest!).",
    "Try to balance a spoon on your nose.",
    "Make up a silly sound effect for something nearby.",
    "Share a song that's stuck in your head.",
    "Do a dramatic reading of a random sentence.",
    "Tell us your favorite color and why.",
    "Pretend to be a news reporter in your next comment.",
    "Try to make a tower of three objects near you.",
    "Share a funny nickname you have or had.",
    "Do a quick impression of a celebrity.",
    "Describe your ideal vacation in three emojis.",
    "Tell us the last thing you ate.",
    "Try to juggle two things (safely!).",
    "Make up a silly slogan for a common household item.",
    "Share a random thought you just had.",
    "Pretend to be a pirate in your next comment.",
    "Try to whistle a song you like.",
    "Describe your favorite book or movie in three words.",
    "Tell us something you're looking forward to.",
    "Do a little finger puppet show.",
    "Share a funny autocorrect story.",
    "Pretend to be a weather reporter in your next comment.",
    "Try to make a funny shadow puppet.",
    "Describe your favorite season and why.",
    "Tell us one of your pet peeves (in a lighthearted way!).",
    "Do a quick robot dance.",
    "Share a silly superstition you know.",
    "Pretend to be a chef in your next comment.",
    "Try to balance a book on your head for 10 seconds.",
    "Describe your favorite animal and why.",
    "Tell us something you learned recently.",
    "Do a quick mime of an everyday activity.",
    "Share a funny thing a pet or child has done.",
    "Pretend to be a sports commentator in your next comment.",
    "Try to make a funny sound with your mouth.",
    "Describe your favorite drink using only colors.",
    "Tell us something that makes you laugh."
]

def handle(comment):
    if comment.body.lower().startswith("!dare"):
        comment.reply(random.choice(DARES))
