import random

INSULTS = [
    "You're not the sharpest knife in the drawer, are you?",
    "You're like a cloud... when you disappear, it's a beautiful day.",
    "You're proof that even evolution takes a break sometimes.",
    "You bring everyone so much joy... when you leave the room.",
    "You have something on your chin... no, the third one down.",
    "Were you born on a highway? Because that's where most accidents happen.",
    "I've had coffee mugs with more personality than you.",
    "Somewhere out there, there's a tree working very hard to produce oxygen for you. I suggest you go and apologize.",
    "I'm not saying you're dumb, but you could trip over a cordless phone.",
    "Is your brain made of sponges? Because it soaks up everything and squeezes out nothing.",
    "I've met garden gnomes with more charisma.",
    "You're about as useful as a screen door on a submarine.",
    "If brains were dynamite, you wouldn't have enough to blow your nose.",
    "I've had weekends longer than your attention span.",
    "You're like a broken pencil... pointless.",
    "I'm trying to imagine you with a personality, but I can't.",
    "You're not the brightest bulb in the chandelier.",
    "I've seen more intelligent life forms in a petri dish.",
    "You're like the human version of a participation trophy.",
    "I've had conversations with rocks that were more stimulating.",
    "You're about as exciting as watching paint dry.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "You're like a riddle wrapped in an enigma wrapped in a vest.",
    "I've forgotten more than you ever knew.",
    "You're a special kind of special.",
    "I'm not saying you're slow, but a glacier moves faster.",
    "You're like a broken record... repeating the same nonsense.",
    "I've seen statues with more expression.",
    "You're the reason they invented the 'undo' button.",
    "If you were a spice, you'd be flour.",
    "You're like a dictionary with missing words.",
    "I've had dreams that made more sense than you.",
    "You're about as subtle as a brick to the face.",
    "If you were a song, you'd be elevator music.",
    "I've argued with toddlers who had a better grasp of reality.",
    "You're like a blank canvas... utterly devoid of anything interesting.",
    "If you were a plant, you'd be a weed.",
    "I've seen cardboard cutouts with more depth.",
    "You're about as sharp as a marble.",
    "If you were a flavor, you'd be unsalted crackers.",
    "I've had more engaging conversations with my shadow.",
    "You're like a VHS tape in a streaming world.",
    "If you were a tool, you'd be a butter knife.",
    "I've seen snails move with more urgency.",
    "You're like a website with no content.",
    "If you were a drink, you'd be lukewarm tap water.",
    "I've had more stimulating interactions with spam emails.",
    "You're like a silent movie... without the charm.",
    "If you were a weather condition, you'd be a light drizzle on a Monday.",
    "I've seen paint dry with more enthusiasm.",
    "You're like a book with all the pages ripped out.",
    "If you were a game, you'd be solitaire.",
    "I've had more profound thoughts while staring at the ceiling.",
    "You're like a broken compass... consistently wrong.",
    "If you were a dance, you'd be the awkward shuffle.",
    "I've seen mannequins with more life.",
    "You're like a song stuck on repeat... and it's not a good song.",
    "If you were a piece of furniture, you'd be a wobbly stool.",
    "I've had more engaging conversations with my pet rock.",
    "You're like a movie with no plot."
]

def handle(comment):
    if comment.body.lower().startswith("!insult"):
        comment.reply(random.choice(INSULTS))
