import random

QUOTES = [
    "Keep going, you're doing great!",
    "Every day is a second chance.",
    "You are stronger than you think.",
    "Small steps every day!",
    "Believe in yourself!",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "Our greatest glory is not in never failing, but in rising up every time we fail.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The journey of a thousand miles begins with a single step.",
    "You are capable of amazing things.",
    "Don't be afraid to shine.",
    "Make today amazing.",
    "The power to be better is within you.",
    "Progress, not perfection.",
    "You've got this!",
    "Stay positive, work hard, make it happen.",
    "The best is yet to come.",
    "Dream bigger than you think you can.",
    "Your efforts will pay off.",
    "Every challenge is an opportunity to grow.",
    "Be the change you wish to see in the world.",
    "The only limit is the one you set yourself.",
    "You are enough.",
    "Embrace the journey.",
    "Take the risk or lose the chance.",
    "The time is always right to do what is right.",
    "Let your hopes, not your hurts, shape your future.",
    "Do what you can, with what you have, where you are.",
    "The sun will rise and we will try again.",
    "You are resilient.",
    "Your attitude determines your direction.",
    "Happiness is an inside job.",
    "Choose joy.",
    "Be kind to yourself.",
    "Celebrate every small victory.",
    "You are making a difference.",
    "Your perspective changes everything.",
    "Focus on the good.",
    "Believe in the power of yet.",
    "The best view comes after the hardest climb.",
    "You are worthy of your dreams.",
    "Don't give up on what you want to achieve.",
    "Make your own sunshine.",
    "The world needs your unique talents.",
    "You have the strength to overcome anything.",
    "Keep your eyes on the stars and your feet on the ground.",
    "Be a voice, not an echo.",
    "Your story matters.",
    "Create the life you want to live.",
    "The universe has your back.",
    "Trust the process.",
    "Everything will be okay in the end. If it's not okay, it's not the end.",
    "Let your light shine.",
    "You are a work in progress.",
    "Be patient with yourself.",
    "Growth takes time.",
    "Every setback is a setup for a comeback.",
    "You are loved and appreciated."
]

def handle(comment):
    if comment.body.lower().startswith("!motivate"):
        comment.reply(random.choice(QUOTES))
