import random

RIZZ_STYLES = {
    "spicy": [
        "Is your name Google? Because you have everything I've been searching for.",
        "Do you believe in love at first sight, or should I walk by again?",
        "Are you a parking ticket? Because you've got 'fine' written all over you.",
        "If you were a vegetable, you'd be a cute-cumber.",
        "Do you have a name, or can I call you mine?",
        "Are you a bank loan? Because you have my interest.",
        "I'm not a photographer, but I can picture us together.",
        "Is your dad a baker? Because you're a cutie pie.",
        "If kisses were snowflakes, I'd send you a blizzard.",
        "Are you a Wi-Fi hotspot? Because I feel a connection.",
        "You must be a broom, 'cause you just swept me off my feet.",
        "Is your name Ariel? Because we mermaid for each other.",
        "Do you like raisins? How about a date?",
        "Something's wrong with my eyes, I can't take them off you.",
        "I'm learning about important dates in history. Wanna be one of them?",
        "If you were a song, you'd be my favorite on repeat.",
        "Are you a puzzle? Because I want to figure you out.",
        "Do you have a sunburn, or are you always this hot?",
        "My love for you is like diarrhea, I can't hold it in.",
        "Excuse me, do you have any raisins? No? How about a date then?",
        "I've lost my number, can I have yours?",
        "You're like a fine wine, getting better with every sip... I mean, sight.",
        "If beauty were a crime, you'd be serving a life sentence.",
        "Are you a charger? Because I'm dying without you.",
        "I think I saw you on Spotify as the hottest single.",
        "Is your name winter? Because you'll be coming soon... and I can't wait.",
        "I'm not sure what your name is, but I bet it's as beautiful as you are.",
        "Do you have any spare hearts? Mine seems to have been stolen.",
        "You're the missing piece I've been searching for.",
        "If you were a star, you'd be the brightest one in the galaxy.",
        "I'd say 'God bless you' but it looks like he already did.",
        "Are you a dream? Because I don't want to wake up.",
        "You're so gorgeous, you made me forget my pickup line.",
        "Can I follow you home? My parents always told me to follow my dreams.",
        "I was wondering if you're an artist because you're so good at drawing me in.",
        "If I had a rose for every time I thought of you, I'd be walking through an eternal garden.",
        "Do you know CPR? Because you take my breath away.",
        "You look familiar, didn't we take a class together? Oh, that's right, it was chemistry.",
        "I'm not flirting, I'm just being extra friendly to someone extra attractive.",
        "If you were a fruit, you'd be a fine-apple.",
        "Is your name melody? Because you're stuck in my head.",
        "I've been told I have a great personality... want to see it in person?",
        "Are you a compass? Because I feel lost without your direction.",
        "If you were a book, you'd be one I couldn't put down.",
        "You're like a magnet, I'm so attracted to you.",
        "Do you believe in magic? Because when I look at you, everything else disappears.",
        "I'm not a genie, but I can make your wishes come true... starting with a date.",
        "Are you a shooting star? Because you make my wishes come true.",
        "If you were a time of day, you'd be 'a little after awesome'.",
        "You're not just a snack, you're a whole damn meal."
    ],
    "nice": [
        "Your smile is contagious.",
        "You have a wonderful sense of humor.",
        "It's always a pleasure talking to you.",
        "You have such a kind heart.",
        "You're a truly genuine person.",
        "I admire your positive attitude.",
        "You make the world a brighter place.",
        "Your kindness shines through everything you do.",
        "You're someone people can really count on.",
        "Being around you is always uplifting.",
        "You have a beautiful spirit.",
        "Your thoughtfulness is much appreciated.",
        "You're a ray of sunshine.",
        "You have a remarkable way of making people feel comfortable.",
        "Your passion is inspiring.",
        "You're intelligent and kind – a rare combination.",
        "You have a gift for making people feel seen.",
        "Your empathy is truly touching.",
        "You're a wonderful listener.",
        "You bring joy to those around you.",
        "Your strength and resilience are admirable.",
        "You have a lovely way of expressing yourself.",
        "You're a true friend.",
        "Your generosity is heartwarming.",
        "You have a beautiful mind.",
        "Your creativity is inspiring.",
        "You approach life with such grace.",
        "You have a talent for making people laugh.",
        "Your honesty is refreshing.",
        "You're someone to look up to.",
        "Your warmth is inviting.",
        "You have a knack for making things better.",
        "Your perspective is always valuable.",
        "You're a truly special person.",
        "Your support means a lot.",
        "You have a wonderful laugh.",
        "Your enthusiasm is contagious.",
        "You have a beautiful aura.",
        "Your presence is calming.",
        "You have a way of making everyone feel included.",
        "Your dedication is impressive.",
        "You have a beautiful soul.",
        "Your insights are always helpful.",
        "You're a natural at making connections.",
        "Your optimism is infectious.",
        "You have a beautiful singing voice (if you know they do!).",
        "Your artistic talents are amazing (if applicable!).",
        "You're so good at what you do.",
        "It's inspiring to see your passion.",
        "You handle everything with such poise."
    ],
    "normal": [
        "I seem to have lost my phone number. Can I have yours?",
        "Are you from Tennessee? Because you're the only ten I see.",
        "If you were a chicken, you'd be impeccable.",
        "Excuse me, but I think I dropped something... my jaw.",
        "Can I borrow a feeling? I'm a little short on them tonight.",
        "I'm not usually this forward, but I had to tell you that you're lovely.",
        "Do you have any spare change? I need to call my mom and tell her I met the person of my dreams.",
        "I was so captivated by your beauty that I ran into that pole over there. So, yeah, it was worth it.",
        "They say Disneyland is the happiest place on earth. Well, apparently, no one has ever been standing next to you.",
        "Is your name Earl Grey? Because you look like a hot-tea!",
        "I've heard that kissing burns about 6.4 calories a minute. Wanna workout?",
        "If I had a star for every time you brightened my day, I'd have a galaxy in my hand.",
        "I'm not a mathematician, but I'm pretty good with numbers. Tell you what, give me yours and watch what I can do.",
        "Are you a dictionary? Because you add meaning to my life.",
        "I'd never play hide and seek with you because someone like you is impossible to find.",
        "If you were a movie, I'd watch you over and over again.",
        "You must be a keyboard because you're my type.",
        "Are you a metaphor? Because you make my world make sense.",
        "Do you believe in fate? Because I think we're meant to be.",
        "Is your name wifi? Because I'm really feeling a connection.",
        "You're like a good book, I just can't put you down.",
        "If you were a traffic light, I'd turn green every time you passed by.",
        "Are you a camera? Because every time I look at you, I smile.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "You're the reason I believe in love at first sight.",
        "If you were a song, you'd be a hit single.",
        "Are you a garden? Because I've got my hoe.",
        "Do you like space? Because I have a lot of it.",
        "You're not a snack, you're a buffet.",
        "If you were a drink, you'd be a fine wine.",
        "Are you a library book? Because I'm checking you out.",
        "Do you have a map? I keep getting lost in your eyes.",
        "You're like a puzzle, all your pieces fit perfectly with mine.",
        "If you were a day of the week, you'd be Friday.",
        "Are you a shooting star? Because you're dazzling.",
        "Do you play soccer? Because you're a keeper.",
        "You're like a dream I don't want to wake up from.",
        "If you were a superhero, what would your superpower be? Mine would be falling for you.",
        "Are you a phone charger? Because I'm feeling like I'm about to die.",
        "Do you like the stars? I can try to get you some.",
        "You're like a good cup of coffee, you start my day right.",
        "If you were a dance, you'd be the waltz – classic and beautiful.",
        "Are you a key? Because you've unlocked something in me.",
        "Do you like art? Because you're a masterpiece.",
        "You're like a warm blanket on a cold night.",
        "If you were a season, you'd be springtime – full of life and beauty.",
        "Are you a good listener? Because I have a lot to say about you.",
        "Do you like books? Because I want to write our story.",
        "You're like a ray of sunshine on a cloudy day.",
        "If you were a place, you'd be my favorite destination."
    ]
}

def handle(comment):
    body = comment.body.lower()
    if body.startswith("!rizz"):
        parts = body.split()
        if len(parts) >= 3:
            style = parts[1]
            target = parts[2]
            rizz_lines = RIZZ_STYLES.get(style, RIZZ_STYLES["normal"])
            rizz = random.choice(rizz_lines)
            comment.reply(f"{target}, {rizz}")
        else:
            comment.reply("Usage: `!rizz [spicy/nice/normal] [username]`")
