import random

TRUTHS = [
    "What’s the biggest lie you’ve ever told?",
    "What’s your most embarrassing moment?",
    "Have you ever had a crush on someone here?",
    "What’s something you're hiding from your parents?",
    "Have you ever cheated in a game?",
    "What's a secret you've never told anyone?",
    "What's the meanest thing you've ever said to someone?",
    "What's something you pretend to like but actually hate?",
    "What's the most trouble you've ever been in?",
    "What's something you're really insecure about?",
    "Have you ever stolen anything?",
    "What's the worst thing you've ever thought about someone?",
    "What's a time you betrayed someone's trust?",
    "What's a mistake you keep making?",
    "What's something you wish you could change about yourself?",
    "Have you ever lied to get out of something?",
    "What's the most childish thing you still do?",
    "What's a dream you've given up on?",
    "What's something you judge other people for?",
    "What's a time you were really jealous of someone?",
    "Have you ever said something you immediately regretted?",
    "What's something you're afraid of that most people aren't?",
    "What's a habit you know you should break?",
    "What's a time you acted like someone you're not?",
    "What's something you're secretly proud of?",
    "Have you ever pretended to be sick to get out of something?",
    "What's the most embarrassing thing you've ever searched online?",
    "What's a time you took credit for something you didn't do?",
    "What's something you wish you were better at?",
    "What's a time you were really selfish?",
    "Have you ever eavesdropped on a conversation?",
    "What's the silliest argument you've ever had?",
    "What's something you've done that you're not proud of?",
    "What's a time you were really stubborn?",
    "What's something you're secretly obsessed with?",
    "Have you ever spread a rumor about someone?",
    "What's the most awkward date you've ever been on?",
    "What's a time you were really unfair to someone?",
    "What's something you wish you had said but didn't?",
    "Have you ever lied about your age?",
    "What's the most embarrassing thing your parents have caught you doing?",
    "What's a time you really regretted something you did?",
    "What's something you're secretly hoping will happen?",
    "Have you ever pretended not to know someone you know?",
    "What's the worst advice you've ever given?",
    "What's a time you were really rude to someone?",
    "What's something you used to believe that you now know is false?",
    "Have you ever broken something and not told anyone?",
    "What's the most embarrassing song you secretly like?",
    "What's a time you were really impatient?",
    "What's something you're procrastinating on right now?",
    "Have you ever faked an injury?",
    "What's the most embarrassing nickname you've ever had?",
    "What's a time you were really judgmental?",
    "What's something you're secretly worried about?",
    "Have you ever regifted something?",
    "What's the most embarrassing thing you've ever worn?",
    "What's a time you were really bossy?",
    "What's something you're secretly insecure about but pretend not to be?",
    "Have you ever lied about your height or weight?",
    "What's the most embarrassing thing you've ever said in your sleep?"
]

def handle(comment):
    if comment.body.lower().startswith("!truth"):
        comment.reply(random.choice(TRUTHS))
